site/firma/urls.py
"""
Definition of urls for firma.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.conf.urls import include
from django.contrib import admin
import app.forms
import app.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView

admin.autodiscover()


# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/app/content/favicon.ico', permanent=True)),
    url(r'^tyr$', app.views.tyr, name='tyr'),
    url(r'^turkey$', app.views.turkey, name='turkey'),
    url(r'^russia$', app.views.russia, name='russia'),
    url(r'^tunisia$', app.views.tunisia, name='tunisia'),
    url(r'^greece$', app.views.greece, name='greece'),
    url(r'^spain$', app.views.spain, name='spain'),
    url(r'^cyprus$', app.views.cyprus, name='cyprus'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

site/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from.models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class AnketaForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    dov = forms.ChoiceField(label='Насколько Вы довольны нашим веб-сайтом?',
                               choices=[('1','Очень доволен/льна'), ('2','Доволен/льна'), ('3','Скорее доволен/льна'), ('4','Скорее недоволен/льна'), ('5','Недоволен/льна'), ('6','Очень недоволен/льна')],
                               widget=forms.RadioSelect, initial=1)
    rek = forms.ChoiceField(label='Вы бы рекомендовали наш веб-сайт другим людям?',
                               choices=[('1','Несомненно да'), ('2','Вероятно да'), ('3','Я не знаю'), ('4','Вероятно нет'), ('5','Несомненно нет')],
                               widget=forms.RadioSelect, initial=1)
    avto = forms.ChoiceField(label='Собираетесь ли вы путешествовать в ближайшее время?',
                               choices=(('1','Да'), 
                                        ('2','Ещё думаю'),
                                        ('3','Нет')), initial=1)
    notice = forms.BooleanField(label='Получать новости сайта на e-mail?',
                                required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length=7)
    message = forms.CharField(label='Оставьте свой отзыв:',
                              widget=forms.Textarea(attrs={'rows':10, 'cols':40}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog #используемая модель
        fields = ('title', 'description', 'content', 'posted', 'author', 'image',)
        labels = {'title':"Заголовок",'description':"Краткое описание", 'content':"Содержание", 'posted':"Дата", 'author':"Автор", 'image':"Изображение",}

site/app/templates/app/about.html
{% extends "app/layout.html" %} {% block content %}
<h3>{{ title }}</h3></br>
<h3>{{ message }}</h3></br>
<strong>ВэлТур+ — международный туристический оператор, организующий туры для путешественников из России, стран СНГ и Восточной Европы.  </strong> </br>Предлагаем для наших туристов отдых в любой стране мира. Сотрудничаем только с надёжными и проверенными туроператорами России , что обеспечивает безопасность и качество Вашего отдыха.</br>Сотрудники регулярно посещают семинары, рекламные туры с целью ознакомления со страной и отельной базой.Своими наработками мы с удовольствием делимся с нашими клиентами.</br>Главный принцип нашей работы-качественный , внимательный и индивидуальный подход к каждому клиенту.</br>«ВэлТур+» предлагает широкий спектр услуг: туры на отдых, экскурсионные туры(авиа, ж/д, автобус), бронирование отелей по всему миру, бронирование авиабилетов, морские и речные круизы, обучение за рубежом, оформление виз. </br>
За годы успешной работы наша компания приобрела бесценный опыт, о чем свидетельствуют лестные отзывы наших постоянных клиентов.</br>

{% endblock %}

site/app/templates/app/anketa.html
{% extends "app/layout.html" %}

{% block content %}

{% if form != None %}
 <br><h2>Ответьте, пожалуйста, на вопросы:</h2><br>
  <div>
      <form method="post">
      {% csrf_token %}
      <label for="{{form.name.id_for_label}}">{{ form.name.label }}</label>
      {{ form.name }}<br><br>
       <label for="{{form.dov.id_for_label}}">{{ form.dov.label }}</label>
      {{ form.dov }}
      <label for="{{form.rek.id_for_label}}">{{ form.rek.label }}</label><br>
      {{ form.rek }}<br><br>
      <label for="{{form.avto.id_for_label}}">{{ form.avto.label }}</label><br>
      {{ form.avto }}<br><br>
      <label for="{{form.notice.id_for_label}}">{{ form.notice.label }}</label>
      {{ form.notice }}<br><br>
      <label for="{{form.email.id_for_label}}">{{ form.email.label }}</label>
      {{ form.email }}<br><br>
      <label for="{{form.message.id_for_label}}">{{ form.message.label }}</label><br>
      {{ form.message }}<br><br>
    
       <button id="b1" type="submit">
           Отправить
       </button>
      </form>
  </div>
{% else %}
 <br><h2>Спасибо за информацию</h2>
 <h3>Вы сообщили следущее:</h3>
 <u1>
     <li><span>Имя:</span> {{ data.name}}</li>
     <li><span>Насколько Вы довольны нашим веб-сайтом?</span> {{ data.dov}}</li>
     <li><span>Вы бы рекомендовали наш веб-сайт другим людям?</span> {{ data.rek}}</li>
     <li><span>Собираетесь ли вы путешествовать в ближайшее время?</span> {{ data.avto}}</li>
     <li><span>Рассылка:</span> {{ data.notice}}</li>
     <li><span>E-mail:</span> {{ data.email}}</li>
     <li><span>Отзыв:</span> {{ data.message}}</li>
 </u1>
{% endif %}

<script>
    function b1_point() { $('#b1').css('color', 'green'); }
    function b1_unpoint() { $('#b1').css('color', 'black'); }
    function name_focus() { $('#id_name').css('background-color', 'Gainsboro'); }
    function name_blur() { $('#id_name').css('background-color', 'white'); }
    function email_focus() { $('#id_email').css('background-color', 'Gainsboro'); }
    function email_blur() { $('#id_email').css('background-color', 'white'); }
    function message_focus() { $('#id_message').css('background-color', 'Gainsboro'); }
    function message_blur() { $('#id_message').css('background-color', 'white'); }

    $('#b1').mouseover(b1_point);
    $('#b1').mouseout(b1_unpoint);
    $('#id_name').focus(name_focus);
    $('#id_name').blur(name_blur);
    $('#id_email').focus(email_focus);
    $('#id_email').blur(email_blur);
    $('#id_message').focus(message_focus);
    $('#id_message').blur(message_blur);

</script>

{% endblock %}

site/app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{ title }}</h2> <br />
{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}
{% endblock %}

site/app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
    <img src="{{ post_1.image.url }}" alt=«Картинка статьи блога" width="350" height="300"/>
{% endif %}
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}
    <div>
         {{form.as_p}}
         <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>
{% else %}
    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}

{% for comment in comments %}
    <hr/>
    <h7> {{comment.date}} </h7>
    <h5> {{comment.author}} </h5>
    <p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

<p><a href="{% url 'blog' %}"> Назад </a></p>
{% endblock %}

site/app/templates/app/cyprus.html
{% extends "app/layout.html" %} {% block content %}
<h1>{{ title }}</h1></br>
<h3>{{ message }}</h3></br>
<p>Кипр – идеальное место для отдыха. Расположенный в Средиземном море остров с мягкими золотистыми пляжами год от года привлекают все больше туристов. Здесь никогда не бывает скучно. Кипр – это остров танцев. В многочисленных клубах с ночи до утра продолжается веселье. Помимо насыщенной ночной жизни Кипр славится и своими красивыми пейзажами. В нем сочетаются густые кедровые леса и мягкие пляжи. Погода на Кипре всегда теплая, что создает идеальные условия для отдыха. Вам предложат комфортабельные номера в первоклассных отелях, позволяющих в полной мере насладиться атмосферой этого острова.</p>
<h4>Площадь</h4>
<p>Территория Кипра занимает 9250.00 км².</p>
<h4>Население</h4>
<p>На Кипре проживает 793963 человек.</p>
<h4>Язык</h4>
<p>Официальный язык – греческий и турецкий.</p>
<h4>Климат</h4>
<p>Климат на Кипре субтропический средиземноморский. Средняя температура летом +25–35°С, зима - + 10–15°С. Летом достаточно жарко, а зимой дождливо. Лучшим временем для отдыха на Кипре является период с июня по сентябрь.</p>
<h4>Достопримечательности</h4>
<p>На Кипре вы увидите множество достопримечательностей, на которых стоит обратить внимание. В стране постоянно ведутся археологические раскопки. Из достопримечательностей Кипра можно выделить средневековый замок Колосси, искусные мозаики на вилле Диониса, форт Петру ту Ромиу, где по легенде родилась Афродита, церковь святого Лазаря в Ларнаке. В столице Кипра, Никосии, очень много памятников древности. Это и знаменитые венецианские стены, и церковь Трипиотис, восхищающая своим роскошным убранством, и турецкие бани Бюйюк-Хамам, известные еще с доосманских времен. В городе Лимасол находится музей средневековья, где представлены рыцарские доспехи, монеты разных лет и многое другое. Недалеко от города возвышается Лимассольский замок, переживший войны и стихийные бедствия. У любого из городов Кипра есть своя интересная история, каждый исторический памятник хранит свою увлекательную легенду.</p>
{% endblock %}

site/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h2>Туристическая фирма "ВэлТур+"</h2>
    <p class="lead">"ВэлТур+" - отдых на любой вкус! Мы гарантируем надежность и безопасность сотрудничества, так как имеем безупречную репутацию, бережем имидж компании и сотрудничаем исключительно с проверенными и надежными туроператорами. Мы предоставляем самый широкий ассортимент путешествий и рады предложить Вам страны и предложения на любой вкус и кошелек.</p>
    <p><a href="{% url 'about' %}" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Турция</h2>
        <p>
           Отдых на побережье солнечной Турции радует теплым морем, отличным сервисом и любимым "Все включено". Но отдых можно разнообразить зажигательными концертами, живой музыкой и красочными шоу, которые проходят прямо на территории отеля.
        </p>
        <p><a class="btn btn-default" href="{% url 'turkey' %}">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Россия</h2>
        <p>Туристические возможности России огромны, как и сама страна. Можно каждый год открывать для себя что-то новое и ни разу не повториться. </p>
        <p><a class="btn btn-default" href="{% url 'russia' %}">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Тунис</h2>
        <p>Страна, где Европа встречается с арабской Африкой. Сюда приезжают, в первую очередь, за идеальным пляжным отдыхом: мелкий белый песок, чистейшее море, комфортабельные отели - на любом курорте Туниса всего этого будет в избытке.</p>
        <p><a class="btn btn-default" href="{% url 'tunisia' %}">Узнать больше &raquo;</a></p>
    </div>
</div>

{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
        <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
        <div class="carousel-inner" role="listbox">
                <div class="item active">
                        <img src="{% static 'app/content/banner1.svg'%} " alt="Первый слайд" class="img-responsive" />
                        <div class="carousel-caption" role="option">
                                <p>
                                        О нас
                                        <a class="btn btn-default" href="{% url 'about' %}">
                                                Читать далее
                                            </a>
                                    </p>
                            </div>
                    </div>
                <div class="item">
                        <img src="{% static 'app/content/banner2.svg'%}" alt="Второй слайд"  class="img-responsive" />
                        <div class="carousel-caption" role="option">
                                <p>
                                        Полезные ресурсы
                                        <a class="btn btn-default" href="{% url 'links' %}">
                                                Читать далее
                                            </a>
                                    </p>
                            </div>
                    </div>
                <div class="item">
                        <img src=" {% static 'app/content/banner3.svg'%} " alt="Третий слайд"  class="img-responsive" />
                        <div class="carousel-caption" role="option">
                                <p> 
                                        Блог
                                        <a class="btn btn-default" href="{% url 'blog' %}">
                                                Читать далее
                                            </a>
                                    </p>
                            </div>
                    </div>
            </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
    </div>
{% endblock %}

site/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}ВэлТур+</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/logo.png' %}" alt="logo"/> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная страница</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'tyr' %}" >Туры</a>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'anketa' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li> 
                    {% if not user.is_authenticated %}
                <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} ВэлТур+ </p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

site/app/templates/app/links.html
<!DOCTYPE html>
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block content %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <h2>{{ title }}</h2>
<a href ="https://www.airpano.ru/" target="_blank"> <img src="{% static 'app/content/logo1.png' %}" alt="Logo 1"/></a></ul>
<a href ="https://tonkosti.ru/" target="_blank"> <img src="{% static 'app/content/logo2.svg' %}" alt="Logo 1"/></a></ul>
<a href ="https://www.tripadvisor.ru/" target="_blank"> <img src="{% static 'app/content/logo3.svg' %}" alt="Logo 1"/></a></ul>
</head>
<body>

</body>
</html>
{% endblock %}

site/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
{% csrf_token %}
<ul class="nav navbar-nav navbar-right">
<li><span class="navbar-brand">Добро пожаловать, {{ user.username }}!</span></li>
<li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
</ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
<li><a href="{% url 'login' %}">Войти в аккаунт</a></li>
</ul>

{% endif %}

site/app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}
    <h3>Добавить статью</h3>
    <form method="POST" enctype="multipart/form-data"  >  {% csrf_token %} {{ form.as_p }}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default" > Сохранить статью </button>
    </div>
    </form>
{% endblock %}

site/app/templates/app/russia.html
{% extends "app/layout.html" %} {% block content %}
<h1>{{ title }}</h1></br>
<h3>{{ message }}</h3></br>
<p>Россия богата историческими памятниками прошлого, а также многочисленными природными достопримечательностями. Многих великих писателей и художников вдохновляли бескрайние российские просторы, синие глади озер, сочная зелень густых лесов, старинные белокаменные церкви и монастыри. Историческими и культурными центрами страны являются Москва и Санкт-Петербург. Своей многовековой историей привлекают также города «Золотого кольца»: Александров, Боголюбово, Владимир, Гороховец, Иваново, Кострома, Переславль-Залесский, Муром, Ростов Великий, Сергиев Посад, Суздаль, Углич, Ярославль и другие.</p>
<h4>Площадь</h4>
<p>Территория России занимает 17075400.00 км².</p>
<h4>Население</h4>
<p>В России проживает 141183200 человек.</p>
<h4>Язык</h4>
<p>Государственным языком является русский.</p>
<h4>Климат</h4>
<p>Территория страны разделена на арктические, субарктические, умеренные и субтропические климатические пояса. На большей части России преобладает континентальный и умеренно-континентальный климат с коротким нежарким летом и длинной холодной зимой. Средняя январская температура составляет от -16°С до -9°С, средняя июльская температура - от 13°С до 23°С. На юге Дальнего Востока климат умеренный муссонный со средними температурами января от 0°С до -5°С, июля - около 13°С. Самым холодным регионом страны является Сибирь. Отдых в России возможен круглый год.</p>
<h4>Достопримечательности</h4>
<p>Москва славится многочисленными архитектурными достопримечательностями. Здесь находятся такие символы города, как Кремль, Собор Василия Блаженного, Храм Христа Спасителя, а также множество театров, художественных галерей и выставочных залов. Санкт-Петербург или “Северная Венеция” известен своим прекрасно сохранившимся центром, в котором расположены великолепный Зимний дворец, здание Университета, Адмиралтейство, Казанский собор, Собор Спаса-на-Крови и многое другое. Города “Золотого кольца” славятся своими церквями и монастырями. В Суздале стоит посетить знаменитый Суздальский Кремль, такие монастырские ансамбли, как Васильевсий, Покровский и Спасо Евфимиевский, Церковь Казанской иконы Божьей Матери, Церковь Воскресения и многое другое. Город Владимир известен Успенским и Дмитриевским собором, Храмом Михаила Архангела, а также многочисленными церквями: Троицкой, Никитской и церковью Николая Чудотворца. Ярославль славится Спасо-Преображенским собором, Церковью Ильи Пророка и Иоанна Предтечи. Символом Сергиева Посада является ансамбль Троице-Сергиевой Лавры. Ростов Великий, считающийся жемчужиной “Золотого кольца”, известен белокаменным Ростовским кремлем, а также великолепным ансамблем Спасо-Яковлевского монастыря. Почти каждый из городов России обладает своим колоритом и восхищает удивительными памятниками древности.</p>
{% endblock %}

site/app/templates/app/tunisia.html
{% extends "app/layout.html" %} {% block content %}
<h1>{{ title }}</h1></br>
<h3>{{ message }}</h3></br>
<p>Тунис – это страна, удивительным образом сочетающая в себе восточные и европейские черты. Поездки по Сахаре, прогулки на верблюдах, талассотерапия, посещение шумных рынков и красивых мечетей – все это придает Тунису удивительный восточный колорит. Развитая инфраструктура первоклассных отелей, прекрасные пляжи и прозрачное море, чистота городов и вежливость населения добавляют стране европейские черты. Разнообразие видов отдыха по относительно низким ценам делает Тунис одним из популярных курортов мира.</p>
<h4>Площадь</h4>
<p>Территория Туниса занимает 163610.00 км².</p>
<h4>Население</h4>
<p>В Тунисе проживает 10383577 человек.</p>
<h4>Язык</h4>
<p>Официальный язык - арабский. Также население говорит и на французском. В туристических зонах понимают английский язык.</p>
<h4>Климат</h4>
<p>Климат в Тунисе умеренный средиземноморский. Зима мягкая, а лето сухое и жаркое. Средняя температура декабря +16С, июля - +26С. Самый жаркий месяц – август. Температура воздуха достигает +45-50С. Лучшее время для отдыха в Тунисе – период с сентября по ноябрь и с марта по июнь.</p>
<h4>Достопримечательности</h4>
<p>Тунис известен своим знаменитым Карфагеном, одним из величайших городов древности. Туристы со всего мира съезжаются и в город Дугга, сохранивший античный облик со времен правления римлян. Среди достопримечательностей можно отметить Капитолий, посвященный Юпитеру, Юноне и Минерве, святилище Юноны Целесты, а также Мавзолей пунической эпохи. В городе Эль Джем находится третий в мире по величине римский Колизей. Город Кайруан славится своими фабриками ковровых изделий. Ковры вышиваются по старинной восточной традиции. Именно поэтому они так красивы и пользуются большим спросом среди туристов. В Монастире расположен Дворец конгрессов, а также мавзолей Бургибы. В городе Махдия стоит прогуляться по старому кварталу Медина, окруженному древними крепостными стенами. Главной достопримечательностью города является крепость Борж эр-Рас, в древности использовавшаяся в качестве тюрьмы. На остров Джерба уже многие столетия подряд собираются паломники, чтобы посетить древнюю синагогу Гриба.</p>
{% endblock %}

site/app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}
   
<div>
      <h1>Вьетнам, Сайгон</h1>  
        <VIDEO src="/media/video1.mp4" controls="controls" width="400" height="250" poster="/media/poster1.jpg"></VIDEO>
    </div>
<hr/>
<div>
      <h1>Воды, пальмовые деревья</h1>  
        <VIDEO src="/media/video2.mp4" controls="controls" width="400" height="250" poster="/media/poster2.jpg"></VIDEO>
    </div>
    
{% endblock %}